In [3]:
QQP_dev = './test.tsv'
t_texts = []
label = []
with open(QQP_dev, 'r', encoding='utf-8') as f:
    lcount = 0
    for line in f:
        if lcount > 0:
            lcount += 1
            line = line.strip().split("\t")
#             all_texts.append(line[3])
#             all_texts.append(line[4])
            try:
                t_texts.append(line[3])
                t_texts.append(line[4])
                label.append(line[5])
            except:
                pass
        else:
            lcount += 1
            continue

In [4]:
len(label) # 总测试样本数

40430

In [7]:
label = [int(i) for i in label]
label[:5]

[0, 0, 1, 0, 0]

In [8]:
sum(label) # is_duplicate 的样本数 

14885

In [9]:
non_duplicate = label.count(0)
print(non_duplicate)
duplicate = label.count(1)
print(duplicate)

25545
14885


In [32]:
import numpy as np
len(np.where([0, 0, 1, 0]==[1, 1, 1, 0])[0])

0

In [35]:
np.where([1,0,1,0,0] == [1,0,0,0,1])

(array([], dtype=int64),)

In [38]:
np.where([1,0,1,0,0] == [1,1,1,1,1])

(array([], dtype=int64),)

In [54]:
a = np.array([1,1,1,0,1])
b = np.array([1,1,0,0,1])
t = np.where(a==b)[0]
t

array([0, 1, 3, 4])

In [55]:
c = np.array([1,1,1,1,1])
p = np.where(a==c)[0]
p

array([0, 1, 2, 4])

In [56]:
np.intersect1d(t, p)

array([0, 1, 4])